name: Deploy and run
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Pass branch and repo to env vars
        run: |
          echo REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo BRANCH_NAME=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        run: |
          echo ${{secrets.GHCR_PAT_SECRET}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}:${{env.BRANCH_NAME}} .
      - name: Tag image
        run: |
          docker tag ghcr.io/${{ env.REPO_NAME }}:${{env.BRANCH_NAME}} ghcr.io/${{ env.REPO_NAME }}:${{env.BRANCH_NAME}}-${{ github.run_id }}
          docker tag ghcr.io/${{ env.REPO_NAME }}:${{env.BRANCH_NAME}} ghcr.io/${{ env.REPO_NAME }}:${{env.BRANCH_NAME}}-latest
      - name: Push to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:${{env.BRANCH_NAME}}-${{ github.run_id }}
          docker push ghcr.io/${{ env.REPO_NAME }}:${{env.BRANCH_NAME}}-latest
      - name: Run tests
        run: |
          docker run --rm -v $(pwd)/cypress/videos:/cypress/videos -v $(pwd)/cypress/screenshots:/cypress/screenshots ghcr.io/${{ env.REPO_NAME }}:${{env.BRANCH_NAME}}-${{ github.run_id }} cypress.config.ts
      - name: Save artifacts
        uses: actions/upload-artifact@main
        with:
          name: artifacts for ${{env.BRANCH_NAME}}-${{ github.run_id }}
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 3
